### ISSUE TITLE
Change repo layout for github.io

### ISSUE THREAD

**Issue by teodutu** [security-summer-school/template-public#11]
We migrated all of our tracks to github.io [1]. This requires some modifications to the structure of each repository:
- Rename session documentation files from `README.md` to `index.md`
- Rename the Markdown file at the root of the repository from `README.md` to `_index.md`
- Add a Github action that updates the content on github.io (where each repository is imported as a submodule).
This step may be left as a stub / not functional in order not to have Github action failures upon each merged PR.

[1] https://github.com/security-summer-school/security-summer-school.github.io

**Comment by gabrielmocanu** [comment]
Done.
